//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data
{
    using System;
    using System.Collections.Generic;using Asya.Util.Wpf.Common.Library.Entity;
    
    public partial class Order_Detail :  BaseEntity
    {
        private int _order_ID;
    	public int Order_ID 
    	{ 
    		get { return _order_ID; } 
    		set
    		{
    			if (value != _order_ID) {
    				_order_ID = value;
    				 OnPropertyChanged("Order_ID");
    			}
    		} 
    	}
    
        private int _product_ID;
    	public int Product_ID 
    	{ 
    		get { return _product_ID; } 
    		set
    		{
    			if (value != _product_ID) {
    				_product_ID = value;
    				 OnPropertyChanged("Product_ID");
    			}
    		} 
    	}
    
        private decimal _unit_Price;
    	public decimal Unit_Price 
    	{ 
    		get { return _unit_Price; } 
    		set
    		{
    			if (value != _unit_Price) {
    				_unit_Price = value;
    				 OnPropertyChanged("Unit_Price");
    			}
    		} 
    	}
    
        private short _quantity;
    	public short Quantity 
    	{ 
    		get { return _quantity; } 
    		set
    		{
    			if (value != _quantity) {
    				_quantity = value;
    				 OnPropertyChanged("Quantity");
    			}
    		} 
    	}
    
        private float _discount;
    	public float Discount 
    	{ 
    		get { return _discount; } 
    		set
    		{
    			if (value != _discount) {
    				_discount = value;
    				 OnPropertyChanged("Discount");
    			}
    		} 
    	}
    
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
