//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data
{
    using System;
    using System.Collections.Generic;using Asya.Util.Wpf.Common.Library.Entity;
    
    public partial class Order :  BaseEntity
    {
        public Order()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }
    
        private int _order_ID;
    	public int Order_ID 
    	{ 
    		get { return _order_ID; } 
    		set
    		{
    			if (value != _order_ID) {
    				_order_ID = value;
    				 OnPropertyChanged("Order_ID");
    			}
    		} 
    	}
    
        private string _customer_ID;
    	public string Customer_ID 
    	{ 
    		get { return _customer_ID; } 
    		set
    		{
    			if (value != _customer_ID) {
    				_customer_ID = value;
    				 OnPropertyChanged("Customer_ID");
    			}
    		} 
    	}
    
        private Nullable<int> _employee_ID;
    	public Nullable<int> Employee_ID 
    	{ 
    		get { return _employee_ID; } 
    		set
    		{
    			if (value != _employee_ID) {
    				_employee_ID = value;
    				 OnPropertyChanged("Employee_ID");
    			}
    		} 
    	}
    
        private string _ship_Name;
    	public string Ship_Name 
    	{ 
    		get { return _ship_Name; } 
    		set
    		{
    			if (value != _ship_Name) {
    				_ship_Name = value;
    				 OnPropertyChanged("Ship_Name");
    			}
    		} 
    	}
    
        private string _ship_Address;
    	public string Ship_Address 
    	{ 
    		get { return _ship_Address; } 
    		set
    		{
    			if (value != _ship_Address) {
    				_ship_Address = value;
    				 OnPropertyChanged("Ship_Address");
    			}
    		} 
    	}
    
        private string _ship_City;
    	public string Ship_City 
    	{ 
    		get { return _ship_City; } 
    		set
    		{
    			if (value != _ship_City) {
    				_ship_City = value;
    				 OnPropertyChanged("Ship_City");
    			}
    		} 
    	}
    
        private string _ship_Region;
    	public string Ship_Region 
    	{ 
    		get { return _ship_Region; } 
    		set
    		{
    			if (value != _ship_Region) {
    				_ship_Region = value;
    				 OnPropertyChanged("Ship_Region");
    			}
    		} 
    	}
    
        private string _ship_Postal_Code;
    	public string Ship_Postal_Code 
    	{ 
    		get { return _ship_Postal_Code; } 
    		set
    		{
    			if (value != _ship_Postal_Code) {
    				_ship_Postal_Code = value;
    				 OnPropertyChanged("Ship_Postal_Code");
    			}
    		} 
    	}
    
        private string _ship_Country;
    	public string Ship_Country 
    	{ 
    		get { return _ship_Country; } 
    		set
    		{
    			if (value != _ship_Country) {
    				_ship_Country = value;
    				 OnPropertyChanged("Ship_Country");
    			}
    		} 
    	}
    
        private Nullable<int> _ship_Via;
    	public Nullable<int> Ship_Via 
    	{ 
    		get { return _ship_Via; } 
    		set
    		{
    			if (value != _ship_Via) {
    				_ship_Via = value;
    				 OnPropertyChanged("Ship_Via");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _order_Date;
    	public Nullable<System.DateTime> Order_Date 
    	{ 
    		get { return _order_Date; } 
    		set
    		{
    			if (value != _order_Date) {
    				_order_Date = value;
    				 OnPropertyChanged("Order_Date");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _required_Date;
    	public Nullable<System.DateTime> Required_Date 
    	{ 
    		get { return _required_Date; } 
    		set
    		{
    			if (value != _required_Date) {
    				_required_Date = value;
    				 OnPropertyChanged("Required_Date");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _shipped_Date;
    	public Nullable<System.DateTime> Shipped_Date 
    	{ 
    		get { return _shipped_Date; } 
    		set
    		{
    			if (value != _shipped_Date) {
    				_shipped_Date = value;
    				 OnPropertyChanged("Shipped_Date");
    			}
    		} 
    	}
    
        private Nullable<decimal> _freight;
    	public Nullable<decimal> Freight 
    	{ 
    		get { return _freight; } 
    		set
    		{
    			if (value != _freight) {
    				_freight = value;
    				 OnPropertyChanged("Freight");
    			}
    		} 
    	}
    
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Order_Detail> Order_Details { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
