//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Data
{
    using System;
    using System.Collections.Generic;using Asya.Util.Wpf.Common.Library.Entity;
    
    public partial class Shipper :  BaseEntity
    {
        public Shipper()
        {
            this.Orders = new HashSet<Order>();
        }
    
        private int _shipper_ID;
    	public int Shipper_ID 
    	{ 
    		get { return _shipper_ID; } 
    		set
    		{
    			if (value != _shipper_ID) {
    				_shipper_ID = value;
    				 OnPropertyChanged("Shipper_ID");
    			}
    		} 
    	}
    
        private string _company_Name;
    	public string Company_Name 
    	{ 
    		get { return _company_Name; } 
    		set
    		{
    			if (value != _company_Name) {
    				_company_Name = value;
    				 OnPropertyChanged("Company_Name");
    			}
    		} 
    	}
    
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
